import type { CustomerProfile, AlertObject, AuditLog } from "@/types";
import { getCustomers, saveCustomers, getAlerts, saveAlerts, getAuditLogs, saveAuditLogs } from "@/utils/storage";

const now = new Date();
const iso = (daysAgo = 0) => new Date(now.getTime() - daysAgo * 86400000).toISOString();

const DEFAULT_CUSTOMERS: CustomerProfile[] = [
  {
    id: "C-100421",
    name: "Arjun Mehta",
    segment: "Salaried",
    riskScore: 0.87,
    band: "Critical",
    predictedDefaultProbability: 87,
    estimatedDaysToDelinquency: 14,
    salaryDelayDays: 7.2,
    salaryDropPercent: 22.5,
    savingsDrawdownPercent: 18.3,
    atmWithdrawalSpikeRatio: 2.6,
    lendingAppTxnCount: 5,
    utilityDelayDays: 6.0,
    discretionarySpendDropPercent: 34.0,
    failedAutoDebitCount: 2,
    spendingVolatilityIndex: 1.4,
    debtBurdenRatio: 0.51,
    netCashflow: -12400,
    dataConfidenceScore: 0.91,
    lastUpdated: iso(1),
    recommendedInterventionTier: "Tier 3",
    recommendedInterventionText:
      "Offer payment holiday for 1 month, assign relationship manager call, and present restructuring plan.",
    flags: [
      "Salary Delay Signal",
      "Salary Drop Signal",
      "Savings Drawdown Signal",
      "Lending App Spike",
      "Repayment Missed Risk",
      "Negative Cashflow",
    ],
    notes: "",
    status: "Under Intervention",
    uploadHistory: [
      { uploadId: "u-001a", timestamp: iso(30), riskScore: 0.62, band: "High", txnCount: 48 },
      { uploadId: "u-001b", timestamp: iso(15), riskScore: 0.76, band: "Critical", txnCount: 52 },
      { uploadId: "u-001c", timestamp: iso(1), riskScore: 0.87, band: "Critical", txnCount: 55 },
    ],
  },
  {
    id: "C-100389",
    name: "Priya Nair",
    segment: "Salaried",
    riskScore: 0.68,
    band: "High",
    predictedDefaultProbability: 68,
    estimatedDaysToDelinquency: 18,
    salaryDelayDays: 4.5,
    salaryDropPercent: 14.0,
    savingsDrawdownPercent: 11.2,
    atmWithdrawalSpikeRatio: 1.9,
    lendingAppTxnCount: 3,
    utilityDelayDays: 3.0,
    discretionarySpendDropPercent: 25.0,
    failedAutoDebitCount: 1,
    spendingVolatilityIndex: 0.95,
    debtBurdenRatio: 0.39,
    netCashflow: -4200,
    dataConfidenceScore: 0.85,
    lastUpdated: iso(2),
    recommendedInterventionTier: "Tier 2",
    recommendedInterventionText:
      "Offer flexible EMI date shift, enable partial payment option, and send budgeting insights report.",
    flags: [
      "Salary Delay Signal",
      "Salary Drop Signal",
      "Savings Drawdown Signal",
      "Lending App Spike",
      "Repayment Missed Risk",
    ],
    notes: "",
    status: "Under Intervention",
    uploadHistory: [
      { uploadId: "u-002a", timestamp: iso(28), riskScore: 0.44, band: "Medium", txnCount: 40 },
      { uploadId: "u-002b", timestamp: iso(14), riskScore: 0.58, band: "High", txnCount: 45 },
      { uploadId: "u-002c", timestamp: iso(2), riskScore: 0.68, band: "High", txnCount: 50 },
    ],
  },
  {
    id: "C-100512",
    name: "Rahul Sharma",
    segment: "Self-employed",
    riskScore: 0.73,
    band: "High",
    predictedDefaultProbability: 73,
    estimatedDaysToDelinquency: 16,
    salaryDelayDays: 9.0,
    salaryDropPercent: 30.0,
    savingsDrawdownPercent: 22.0,
    atmWithdrawalSpikeRatio: 2.1,
    lendingAppTxnCount: 4,
    utilityDelayDays: 5.0,
    discretionarySpendDropPercent: 40.0,
    failedAutoDebitCount: 1,
    spendingVolatilityIndex: 1.1,
    debtBurdenRatio: 0.44,
    netCashflow: -8700,
    dataConfidenceScore: 0.79,
    lastUpdated: iso(3),
    recommendedInterventionTier: "Tier 2",
    recommendedInterventionText:
      "Offer flexible EMI date shift, enable partial payment option, reduce credit limit to avoid overspending.",
    flags: [
      "Salary Delay Signal",
      "Salary Drop Signal",
      "Savings Drawdown Signal",
      "Cash Hoarding Behavior",
      "Lending App Spike",
      "High Volatility Spend",
    ],
    notes: "",
    status: "Active",
    uploadHistory: [
      { uploadId: "u-003a", timestamp: iso(25), riskScore: 0.50, band: "Medium", txnCount: 38 },
      { uploadId: "u-003b", timestamp: iso(10), riskScore: 0.68, band: "High", txnCount: 43 },
      { uploadId: "u-003c", timestamp: iso(3), riskScore: 0.73, band: "High", txnCount: 47 },
    ],
  },
  {
    id: "C-100298",
    name: "Sneha Patel",
    segment: "Salaried",
    riskScore: 0.41,
    band: "Medium",
    predictedDefaultProbability: 41,
    estimatedDaysToDelinquency: 24,
    salaryDelayDays: 2.0,
    salaryDropPercent: 8.0,
    savingsDrawdownPercent: 5.5,
    atmWithdrawalSpikeRatio: 1.3,
    lendingAppTxnCount: 1,
    utilityDelayDays: 1.5,
    discretionarySpendDropPercent: 12.0,
    failedAutoDebitCount: 0,
    spendingVolatilityIndex: 0.55,
    debtBurdenRatio: 0.28,
    netCashflow: 3200,
    dataConfidenceScore: 0.88,
    lastUpdated: iso(4),
    recommendedInterventionTier: "Tier 1",
    recommendedInterventionText:
      "Send reminder notification about upcoming EMI, offer budgeting insights report.",
    flags: ["Savings Drawdown Signal", "Discretionary Spend Drop"],
    notes: "",
    status: "Active",
    uploadHistory: [
      { uploadId: "u-004a", timestamp: iso(20), riskScore: 0.28, band: "Low", txnCount: 36 },
      { uploadId: "u-004b", timestamp: iso(8), riskScore: 0.35, band: "Medium", txnCount: 40 },
      { uploadId: "u-004c", timestamp: iso(4), riskScore: 0.41, band: "Medium", txnCount: 44 },
    ],
  },
  {
    id: "C-100643",
    name: "Vikram Iyer",
    segment: "Retired",
    riskScore: 0.19,
    band: "Low",
    predictedDefaultProbability: 19,
    estimatedDaysToDelinquency: 28,
    salaryDelayDays: 0,
    salaryDropPercent: 0,
    savingsDrawdownPercent: 2.1,
    atmWithdrawalSpikeRatio: 1.0,
    lendingAppTxnCount: 0,
    utilityDelayDays: 0,
    discretionarySpendDropPercent: 4.0,
    failedAutoDebitCount: 0,
    spendingVolatilityIndex: 0.22,
    debtBurdenRatio: 0.12,
    netCashflow: 14500,
    dataConfidenceScore: 0.94,
    lastUpdated: iso(5),
    recommendedInterventionTier: "Tier 0",
    recommendedInterventionText: "No action required. Continue periodic monitoring.",
    flags: [],
    notes: "",
    status: "Active",
    uploadHistory: [
      { uploadId: "u-005a", timestamp: iso(35), riskScore: 0.17, band: "Low", txnCount: 28 },
      { uploadId: "u-005b", timestamp: iso(18), riskScore: 0.19, band: "Low", txnCount: 30 },
      { uploadId: "u-005c", timestamp: iso(5), riskScore: 0.19, band: "Low", txnCount: 32 },
    ],
  },
  {
    id: "C-100577",
    name: "Anjali Rao",
    segment: "Student",
    riskScore: 0.56,
    band: "High",
    predictedDefaultProbability: 56,
    estimatedDaysToDelinquency: 20,
    salaryDelayDays: 5.0,
    salaryDropPercent: 18.0,
    savingsDrawdownPercent: 14.0,
    atmWithdrawalSpikeRatio: 1.8,
    lendingAppTxnCount: 3,
    utilityDelayDays: 4.5,
    discretionarySpendDropPercent: 28.0,
    failedAutoDebitCount: 1,
    spendingVolatilityIndex: 0.88,
    debtBurdenRatio: 0.36,
    netCashflow: -2100,
    dataConfidenceScore: 0.76,
    lastUpdated: iso(2),
    recommendedInterventionTier: "Tier 2",
    recommendedInterventionText:
      "Offer flexible EMI date shift, enable partial payment option, and send budgeting insights.",
    flags: [
      "Salary Delay Signal",
      "Savings Drawdown Signal",
      "Late Utility Payments",
      "Lending App Spike",
      "Repayment Missed Risk",
    ],
    notes: "",
    status: "Active",
    uploadHistory: [
      { uploadId: "u-006a", timestamp: iso(22), riskScore: 0.38, band: "Medium", txnCount: 34 },
      { uploadId: "u-006b", timestamp: iso(10), riskScore: 0.49, band: "Medium", txnCount: 39 },
      { uploadId: "u-006c", timestamp: iso(2), riskScore: 0.56, band: "High", txnCount: 42 },
    ],
  },
  {
    id: "C-100789",
    name: "Karan Verma",
    segment: "Self-employed",
    riskScore: 0.82,
    band: "Critical",
    predictedDefaultProbability: 82,
    estimatedDaysToDelinquency: 10,
    salaryDelayDays: 0,
    salaryDropPercent: 0,
    savingsDrawdownPercent: 25.0,
    atmWithdrawalSpikeRatio: 3.1,
    lendingAppTxnCount: 6,
    utilityDelayDays: 8.0,
    discretionarySpendDropPercent: 45.0,
    failedAutoDebitCount: 3,
    spendingVolatilityIndex: 1.8,
    debtBurdenRatio: 0.60,
    netCashflow: -15000,
    dataConfidenceScore: 0.88,
    lastUpdated: iso(1),
    recommendedInterventionTier: "Tier 3",
    recommendedInterventionText: "Immediate restructuring required. High risk of default due to cash flow issues.",
    flags: ["Cash Hoarding Behavior", "Lending App Spike", "Negative Cashflow"],
    notes: "",
    status: "Under Intervention",
    uploadHistory: [
      { uploadId: "u-007a", timestamp: iso(30), riskScore: 0.70, band: "High", txnCount: 40 },
    ],
  },
  {
    id: "C-100890",
    name: "Sara Khan",
    segment: "Salaried",
    riskScore: 0.12,
    band: "Low",
    predictedDefaultProbability: 12,
    estimatedDaysToDelinquency: 45,
    salaryDelayDays: 0,
    salaryDropPercent: 0,
    savingsDrawdownPercent: 1.5,
    atmWithdrawalSpikeRatio: 1.1,
    lendingAppTxnCount: 0,
    utilityDelayDays: 0,
    discretionarySpendDropPercent: 2.0,
    failedAutoDebitCount: 0,
    spendingVolatilityIndex: 0.15,
    debtBurdenRatio: 0.10,
    netCashflow: 8000,
    dataConfidenceScore: 0.95,
    lastUpdated: iso(2),
    recommendedInterventionTier: "Tier 0",
    recommendedInterventionText: "Stable financial health. No action required.",
    flags: [],
    notes: "",
    status: "Active",
    uploadHistory: [],
  },
  {
    id: "C-100901",
    name: "Mike Ross",
    segment: "Student",
    riskScore: 0.45,
    band: "Medium",
    predictedDefaultProbability: 45,
    estimatedDaysToDelinquency: 25,
    salaryDelayDays: 0,
    salaryDropPercent: 0,
    savingsDrawdownPercent: 8.0,
    atmWithdrawalSpikeRatio: 1.5,
    lendingAppTxnCount: 2,
    utilityDelayDays: 2.0,
    discretionarySpendDropPercent: 15.0,
    failedAutoDebitCount: 0,
    spendingVolatilityIndex: 0.75,
    debtBurdenRatio: 0.30,
    netCashflow: 500,
    dataConfidenceScore: 0.80,
    lastUpdated: iso(3),
    recommendedInterventionTier: "Tier 1",
    recommendedInterventionText: "Monitor irregular income. Suggest budgeting tools.",
    flags: ["High Volatility Spend"],
    notes: "",
    status: "Active",
    uploadHistory: [],
  },
  {
    id: "C-101012",
    name: "Linda Ray",
    segment: "Retired",
    riskScore: 0.91,
    band: "Critical",
    predictedDefaultProbability: 91,
    estimatedDaysToDelinquency: 7,
    salaryDelayDays: 0,
    salaryDropPercent: 0,
    savingsDrawdownPercent: 40.0,
    atmWithdrawalSpikeRatio: 1.5,
    lendingAppTxnCount: 8,
    utilityDelayDays: 12.0,
    discretionarySpendDropPercent: 60.0,
    failedAutoDebitCount: 4,
    spendingVolatilityIndex: 2.1,
    debtBurdenRatio: 0.75,
    netCashflow: -20000,
    dataConfidenceScore: 0.92,
    lastUpdated: iso(1),
    recommendedInterventionTier: "Tier 3",
    recommendedInterventionText: "Critical intervention needed. Asset liquidation or debt consolidation may be required.",
    flags: ["Savings Drawdown Signal", "Repayment Missed Risk", "Negative Cashflow"],
    notes: "",
    status: "Under Intervention",
    uploadHistory: [],
  },
  {
    id: "C-101123",
    name: "Raj Malhotra",
    segment: "Salaried",
    riskScore: 0.65,
    band: "High",
    predictedDefaultProbability: 65,
    estimatedDaysToDelinquency: 19,
    salaryDelayDays: 3.0,
    salaryDropPercent: 10.0,
    savingsDrawdownPercent: 12.0,
    atmWithdrawalSpikeRatio: 2.2,
    lendingAppTxnCount: 4,
    utilityDelayDays: 4.0,
    discretionarySpendDropPercent: 30.0,
    failedAutoDebitCount: 1,
    spendingVolatilityIndex: 1.2,
    debtBurdenRatio: 0.45,
    netCashflow: -5000,
    dataConfidenceScore: 0.87,
    lastUpdated: iso(2),
    recommendedInterventionTier: "Tier 2",
    recommendedInterventionText: "Proactive engagement recommended. Offer EMI rescheduling.",
    flags: ["Salary Delay Signal", "Lending App Spike"],
    notes: "",
    status: "Active",
    uploadHistory: [],
  },
];

const DEFAULT_ALERTS: AlertObject[] = [
  {
    alertId: "al-001",
    customerId: "C-100421",
    level: "critical",
    title: "Critical Risk – Immediate Action Required",
    detail: "Arjun Mehta has crossed the critical threshold (87). Multiple signals: salary delay, savings drain, and missed repayments.",
    signals: ["Salary Delay Signal", "Savings Drawdown Signal", "Repayment Missed Risk"],
    createdAt: iso(1),
    read: false,
    action: "Intervene",
    priorityScore: 97,
  },
  {
    alertId: "al-002",
    customerId: "C-100389",
    level: "high",
    title: "High Risk – Salary Delay & Lending App Spike",
    detail: "Priya Nair shows salary delayed by 4.5 days and 3 lending app transactions in last 14 days.",
    signals: ["Salary Delay Signal", "Lending App Spike"],
    createdAt: iso(2),
    read: false,
    action: "Intervene",
    priorityScore: 82,
  },
  {
    alertId: "al-003",
    customerId: "C-100512",
    level: "high",
    title: "High Risk – Cash Hoarding & Volatility",
    detail: "Rahul Sharma shows elevated ATM withdrawals (2.1x baseline) and high spending volatility index of 1.1.",
    signals: ["Cash Hoarding Behavior", "High Volatility Spend", "Savings Drawdown Signal"],
    createdAt: iso(3),
    read: false,
    action: "Intervene",
    priorityScore: 77,
  },
  {
    alertId: "al-004",
    customerId: "C-100298",
    level: "medium",
    title: "Medium Risk – Savings Drawdown Detected",
    detail: "Sneha Patel's savings drawdown at 5.5% with slight discretionary spend drop. Monitor closely.",
    signals: ["Savings Drawdown Signal", "Discretionary Spend Drop"],
    createdAt: iso(4),
    read: true,
    action: "Review",
    priorityScore: 43,
  },
  {
    alertId: "al-005",
    customerId: "C-100577",
    level: "high",
    title: "High Risk – Multiple Stress Signals",
    detail: "Anjali Rao shows salary delay, late utility payments, and an active lending app pattern.",
    signals: ["Salary Delay Signal", "Late Utility Payments", "Lending App Spike"],
    createdAt: iso(2),
    read: false,
    action: "Intervene",
    priorityScore: 70,
  },
];

const DEFAULT_AUDIT: AuditLog[] = [
  {
    logId: "log-seed-001",
    type: "UPLOAD",
    actor: "System",
    description: "Seed data loaded: 6 default customers added to portfolio",
    timestamp: iso(1),
    metadata: { customerCount: 6 },
  },
  {
    logId: "log-seed-002",
    type: "RISK_SCORE",
    actor: "System",
    description: "Risk scores computed for all seeded customers",
    timestamp: iso(1),
    metadata: { critical: 1, high: 3, medium: 1, low: 1 },
  },
  {
    logId: "log-seed-003",
    type: "ALERT_GENERATED",
    actor: "System",
    description: "5 alerts generated from seeded customer risk profiles",
    timestamp: iso(1),
    metadata: { alertCount: 5 },
  },
  {
    logId: "log-seed-004",
    type: "INTERVENTION_TRIGGERED",
    actor: "System",
    description: "Tier 3 intervention triggered for C-100421 (Arjun Mehta)",
    timestamp: iso(1),
    metadata: { customerId: "C-100421", tier: "Tier 3" },
  },
];

export function seedDefaultData() {
  const existing = getCustomers();

  // Find customers in DEFAULT that are NOT in existing
  const newCustomers = DEFAULT_CUSTOMERS.filter(
    (def) => !existing.some((ex) => ex.id === def.id)
  );

  if (newCustomers.length > 0) {
    saveCustomers([...existing, ...newCustomers]);
    // console.log(`Seeded ${newCustomers.length} new default customers.`);
  }

  // Only seed alerts/logs if completely empty to avoid duplicates
  const existingAlerts = getAlerts();
  if (existingAlerts.length === 0) {
    saveAlerts(DEFAULT_ALERTS);
  }

  const existingLogs = getAuditLogs();
  if (existingLogs.length === 0) {
    saveAuditLogs(DEFAULT_AUDIT);
  }
}
